# Generated by Django 3.2.19 on 2023-07-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='medical_issue',
            new_name='message',
        ),
    ]
