# Generated by Django 3.2.19 on 2023-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='stage',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('landed', 'Landed'), ('treatment_in_process', 'Treatment in Process'), ('money_in_the_bank', 'Money In The Bank'), ('contacted', 'Contacted'), ('enquiry', 'Enquiry'), ('cancelled', 'Cancelled'), ('succesfully_treated', 'Successfully Treated')], default='enquiry', max_length=50),
        ),
    ]
